### ISSUE TITLE
Add `--ignore`

### ISSUE THREAD

**Issue by ZeroEkkusu** [0xPolygon/storage-layout-checker#7]
Add option to not create reports for contacts with only `new` findings.

How to do this:

Add `--ignore` option to the arguments of `run.sh`.

After `--ignore` values should be specified for what to ignore. In this case we only have `new`.

`--ignore` should be optional.

If `--ignore` is used, but no values are specified, the command should fail, and the user informed what went wrong.

Once `--ignore new` is specified, `run.sh` should relay this to `_reporter.js`.

`_reporter.js` will do everything as before, but right before saving, it should check if `reportNew` contains `🌱`, and no other indicators.

If so, exit `_reporter.js` silently, without generating the report.

**Comment by triggeredcode** [comment]
@ZeroEkkusu Cool, let me try this one.

**Comment by triggeredcode** [comment]
@ZeroEkkusu I have successfully setup the project on the local system, but I am having a little issue with how to use the application, to be more specific: 

1. Where I keep the **contract example.sol in the directory**
2. How to find/create the **commit or tag** as I need that as parameter.

Please refer me to any reading material that can help me.

**Comment by ZeroEkkusu** [comment]
Sure, you're using Foundry, right?

When you `forge init` a new project you will have `src/Counter.sol` in it.
Add the tool to the project as described in the readme.

Then, `git commit` the changes, and you'll have the commit hash.
Use it when you try running the tool.

A report shouldn't be created, since you haven't touched `Counter`.
Now, append some variable to it, and run the tool again. It will create a report with the new variable indicated with `🌱`.

The goal after modifying the tool is for it to not generate a report when there are only new (`🌱`) variables.
You can make changes to it directly in the `lib` folder of the example project, and re-run it to test it.

Once you're done you can copy over the changes to your fork and make a pull request.

**Comment by triggeredcode** [comment]
@ZeroEkkusu Thanks for all the help, I successfully did all the steps and now its working, i have started to work on the main issue.

**Comment by triggeredcode** [comment]
@ZeroEkkusu I am almost done, wanted to run something by you first.

- [ ] 1. Now that I am passing the flag to _reporter.js to whether to ignore or not, do I simply skip over all `🌱` new vars in the for loop condition in case the ignore is true?
- [ ] 2. And in case there is only `🌱` new, then i skip over writing the file silently without any errors.

**Comment by ZeroEkkusu** [comment]
No need to change any logic in the `_reported.js`. You can let it do everything as before.

Right before `_reported.js` creates any files at the end, check if `reportNew` (the string) does contain `🌱` and does not contain `🏴`, `🏳️` `🏁`, `🪦`.

If that's the case, exit.

**Comment by triggeredcode** [comment]
Cool, I will do that, can I know the reason because the  --ignore new will mean ignore the new vars and we are actually not ignoring them but only in the case nothing else is present.

**Comment by ZeroEkkusu** [comment]
Yep, feel free to suggest a better name!

Basically, the idea is:

The tool generates a report, i.e. `./storage_delta`.
The report contains findings, e.g. `src/Counter`.

We want to ignore findings with only `new` detectors.

Open to suggestions.

**Comment by triggeredcode** [comment]
I have a suggestion but maybe its a bit long `--skip-if-only-new` and the values could be `0 or 1`.

**Comment by ZeroEkkusu** [comment]
Let's do `--skip` (as option) `only-new` (as value). We can always change it later.

**Comment by ZeroEkkusu** [comment]
Added in #13.
